---
# molecule/vagrant/playbook2.yml
#
# Regular playbook stuff starts here
#
#
# molecule/lxd/playbook2.yml
#
# Regular playbook stuff starts here
#
#
- name: Converge
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - docker
    users:
      - username: ubuntu
        groups:
          - ubuntu
          # - docker
        append: true
    vagrant_version: 2.2.3
    vagrant_virtualbox_install: false

  roles:
    - role: cjsteel.model
    - role: robertdebock.update
    - role: robertdebock.locale
      vars:
        - locale_lang: en_CA.UTF-8
    - role: cjsteel.pip
    - role: robertdebock.atom
    - role: robertdebock.update
    - role: robertdebock.openvas
