---
# molecule/lxd/playbook2.yml
#
# Regular playbook stuff starts here
#
#
- name: Converge
  hosts: all
  pre_tasks:

    - set_fact: fact_controller_user="{{ lookup('env','USER') }}"
    - debug: var=fact_controller_user

    - set_fact: fact_controller_home="{{ lookup('env','HOME') }}"
    - debug: var=fact_controller_home

    - set_fact: fact_project_path="{{ lookup('pipe','pwd') }}"
    - debug: var=fact_project_path

  vars:
    pip_install_packages:
      - docker
    users:
      - username: ubuntu
        groups:
          - ubuntu
          # - docker
        append: true
    vagrant_version: 2.2.3
    vagrant_virtualbox_install: false

  roles:
    - role: cjsteel.model
    - role: gantsign.fd
    - role: robertdebock.atom
    - role: robertdebock.powertop
    - role: csteel.myrepos
      vars:
        - myrepos_local_user: '{{ fact_controller_user }}'
        - myrepos_local_home: '{{ fact_controller_home }}'
        - myrepos_local_resources_root: '{{ fact_controller_home }}'
