---
# DANGER - HIGH VOLTAGE - boilerplate used for updating to update THIS ROLES molecule scenario files.
#
#
- name: Converge updated provider files
  hosts: all
  vars:

    providers_short_name: model
    providers_galaxy_name: cjsteel.model

    providers_project_directory: "{{ lookup('env', 'PWD') }}"
    # files to be ubpdated should be set to be true
    providers_update_lxd_install_rst: false   # caution - updates this roles molecule scenario files
    providers_update_lxd_molecule_yml: false  # caution - updates this roles molecule scenario files
    providers_update_lxd_playbook_yml: false  # caution - updates this roles molecule scenario files

  pre_tasks:
    - debug:
        var: providers_project_directory
#  roles:
#    - role: cjsteel.providers

# Normal playbook stuff starts here
#
#
- name: Converge
  hosts: all
  vars:
    pip_debug: true
    pip_install_type: 'packages'
    pip_install_from_packages:

      - name: molecule
        state: present
        version: "2.20.0.0a1"
        # parent dir of virtualenv below will be the remote home dir
        virtualenv: .venv/molecule/2.20.0.0a1
        virtualenv_python: python2.7

      - name: docker
        state: present
        virtualenv: .venv/molecule/2.20.0.0a1

    users:
      - username: ubuntu
        groups:
          - docker
        append: true
    vagrant_version: 2.2.3
    vagrant_virtualbox_install: false

  # galaxy roles below must be in projects requirements.yml file in order to work

  roles:
    - role: cjsteel.model
    # - role: cjsteel.pip
    # - role: geerlingguy.docker
    # - role: weareinteractive.users
    # - role: jdauphant.vagrant
